### ISSUE TITLE
Сервис аккаунты к GCP

### ISSUE THREAD

**Issue by bard86** [BadgerSolutions/otus-devops-final-project#21]

**Comment by 9868-08** [comment]
предлагаю использовать учетку гугл моего сына
andresermolaev@gmail.com
CXhhb1i7
облако гугл ему вряд-ли понадобится

**Comment by bard86** [comment]
Вышли приглашения остальным участникам, дай им права для работы с Compute Engine / Network. По возможности через bash скрипт.

https://cloud.google.com/sdk/gcloud/reference

**Comment by ivankuchin85** [comment]
Приглашение получил, однако прав не хватает. @9868-08 надо что-то поправить)

**Comment by 9868-08** [comment]
@ivankuchin85 это известно и я работаю над этим. Можно просто поставить галочки в ГУИ, но на  хочу решить это через gcloud и shell script.

**Comment by TsiguroSD** [comment]
@9868-08  У меня не было приглашения

**Comment by 9868-08** [comment]
ковыряю права доступа. Есть мысль настроить одному полльзователю через ГУИ (пусть будет job.dbarsukov@gmail.com) и скорировать остальным.
считать права получается успешно
gcloud projects get-iam-policy piggymetrics-273206 --flatten=bindings[].members     --format='table(bindings.role)'     --filter=bindings.members:job.dbarsukov@gmail.com --format yaml > 1.yaml
но записать из в GCP не получается. 
gcloud projects set-iam-policy piggymetrics-273206 --format json 1.yaml
ERROR: (gcloud.projects.set-iam-policy) Failed to parse YAML from [1.yaml]: expected a single document in the stream
  in "1.yaml", line 2, column 1
but found another document
  in "1.yaml", line 7, column 1

**Comment by 9868-08** [comment]
права настроены через ГУИ. Удобно смотреть их со вкладки roles
https://photos.app.goo.gl/xBH9xaSq4EYu5an47
