### ISSUE TITLE
Новая учетка в GCP

### ISSUE THREAD

**Issue by bard86** [BadgerSolutions/otus-devops-final-project#24]

**Comment by 9868-08** [comment]
Я предложил существующую учетку, прибил к ней карту, чтобы получить бесплатные кредиты. Зачем заводить новую?

**Comment by bard86** [comment]
Супер! Её и возьмем

**Comment by bard86** [comment]
Закрывай задачу

**Comment by 9868-08** [comment]
спасибо Денису, разобрались с настройками прав доступа в GCP
